# Generated by Django 4.0.2 on 2022-11-28 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('owner', models.CharField(default='', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assetinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.IntegerField()),
                ('ownerID', models.CharField(default='', max_length=20)),
                ('item_id', models.CharField(default='', max_length=20)),
                ('entry_date', models.DateField(default=datetime.datetime.now)),
                ('statusID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Assetstatus',
            fields=[
                ('statusid', models.IntegerField(primary_key=True, serialize=False)),
                ('statusname', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employeeinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empolyeeID', models.IntegerField()),
                ('employeeName', models.CharField(default='', max_length=20)),
                ('departmentId', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=20)),
                ('categoryId', models.CharField(max_length=20)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_manage.assetinfo')),
            ],
        ),
    ]
