# Generated by Django 4.1.3 on 2022-12-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
