# Generated by Django 4.0.2 on 2022-11-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(default='', max_length=20),
        ),
    ]
