# Generated by Django 4.0.2 on 2022-11-01 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0002_asset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
