# Generated by Django 4.1.3 on 2022-11-10 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0003_asset_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assetinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.IntegerField()),
                ('ownerID', models.CharField(default='', max_length=20)),
                ('itemId', models.CharField(max_length=20)),
                ('entry_date', models.DateField(default=datetime.datetime.now)),
                ('statusID', models.CharField(max_length=20)),
            ],
        ),
    ]
