# Generated by Django 4.1.4 on 2022-12-21 16:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0003_alter_asset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='tag_no',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
