# Generated by Django 4.1.4 on 2022-12-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_manage', '0004_alter_assetinfo_tag_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='employeeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
