# Generated by Django 4.1.4 on 2022-12-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0005_alter_employeeinfo_employeename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='email',
        ),
    ]
