# Generated by Django 4.0.2 on 2022-12-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0006_remove_employeeinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='tag_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_manage.asset'),
        ),
    ]
