# Generated by Django 4.0.2 on 2022-12-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0007_alter_assetinfo_tag_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinfo',
            name='ownerID',
        ),
    ]
