# Generated by Django 4.0.2 on 2022-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0008_remove_assetinfo_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
