# Generated by Django 4.0.2 on 2022-12-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0010_alter_assetinfo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
