# Generated by Django 4.1.4 on 2023-01-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0012_assetrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequest',
            name='request_message',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='user_name',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='User_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='request_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
