# Generated by Django 4.1.4 on 2023-01-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0014_assetrequest_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
