# Generated by Django 4.1.4 on 2023-01-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0017_alter_assetrequest_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='asset_manage.asset'),
        ),
    ]
