# Generated by Django 4.1.4 on 2023-01-21 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_manage', '0018_alter_assetrequest_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequest',
            name='User_id',
        ),
        migrations.CreateModel(
            name='Maintenancerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maintenance_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='asset_manage.asset')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
