# Generated by Django 4.1.4 on 2023-01-29 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0019_remove_assetrequest_user_id_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
