# Generated by Django 4.1.4 on 2023-01-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_manage', '0020_maintenancerequest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='User_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
